services:
  - type: web
    name: autumn-job-tracker
    runtime: python
    buildCommand: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: APP_PASSWORD
        value: qiuzhao2026
      - key: PYTHON_VERSION
        value: "3.10.0"
