# ======== 爬虫数据源配置 ========
# 第一期只爬取金融类、互联网类、国央企三种企业

SOURCES = {
    'niuke': {
        'name': '牛客网校招日历',
        'url': 'https://www.nowcoder.com/school/schedule',
        'enabled': True,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
    },
    'ncss': {
        'name': '国家大学生就业服务平台',
        'url': 'https://www.ncss.cn/student/jobs/index.html',
        'enabled': True,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
    },
    'jobonline': {
        'name': '就业在线',
        'url': 'https://www.jobonline.cn/',
        'enabled': True,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
    },
}

# ======== 985高校就业信息网（网页版） ========
# 说明：以下配置为框架模板，enabled=False 表示尚未实现具体解析逻辑
# 如需启用某所学校，请将其 enabled 改为 True 并提供准确的就业信息栏目 URL
# 注意：每所学校的网站结构不同，需要单独编写 HTML 解析规则

UNIVERSITY_SOURCES = {
    # --- 北京 ---
    'uni_pku': {
        'name': '北京大学学生就业指导服务中心',
        'url': 'https://scc.pku.edu.cn/',
        'enabled': True,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '需分析具体栏目 URL 和列表页 HTML 结构',
    },
    'uni_thu': {
        'name': '清华大学学生职业发展指导中心',
        'url': 'http://career.tsinghua.edu.cn/',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '需分析具体栏目 URL 和列表页 HTML 结构',
    },
    'uni_ruc': {
        'name': '中国人民大学就业创业指导中心',
        'url': 'http://rdjy.ruc.edu.cn/',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '需分析具体栏目 URL 和列表页 HTML 结构',
    },
    'uni_buaa': {
        'name': '北京航空航天大学就业信息网',
        'url': 'http://rdjy.ruc.edu.cn/',
        'enabled': True,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_bit': {
        'name': '北京理工大学就业信息网',
        'url': '',
        'enabled': True,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_bnu': {
        'name': '北京师范大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },

    # --- 上海 ---
    'uni_fudan': {
        'name': '复旦大学学生职业发展教育服务中心',
        'url': 'https://career.fudan.edu.cn/',
        'enabled': True,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '需分析具体栏目 URL 和列表页 HTML 结构',
    },
    'uni_sjtu': {
        'name': '上海交通大学就业信息网',
        'url': 'https://www.job.sjtu.edu.cn/',
        'enabled': True,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '需分析具体栏目 URL 和列表页 HTML 结构',
    },
    'uni_tongji': {
        'name': '同济大学学生就业信息网',
        'url': 'https://tj91.tongji.edu.cn/',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_ecnu': {
        'name': '华东师范大学就业信息网',
        'url': '',
        'enabled': True,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },

    # --- 江浙 ---
    'uni_zju': {
        'name': '浙江大学就业指导与服务中心',
        'url': 'http://www.career.zju.edu.cn/',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '需分析具体栏目 URL 和列表页 HTML 结构',
    },
    'uni_nju': {
        'name': '南京大学学生就业指导中心',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_seu': {
        'name': '东南大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },

    # --- 华南 ---
    'uni_sysu': {
        'name': '中山大学学生就业指导中心',
        'url': '',
        'enabled': True,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_scut': {
        'name': '华南理工大学就业信息网',
        'url': 'https://jyzx.scut.edu.cn/',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },

    # --- 华中 ---
    'uni_whu': {
        'name': '武汉大学学生就业指导与服务中心',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_hust': {
        'name': '华中科技大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },

    # --- 川渝 ---
    'uni_scu': {
        'name': '四川大学就业信息网',
        'url': 'http://jy.scu.edu.cn/',
        'enabled': True,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '/index/index/employjob.html',
        'note': '已支持职位列表爬取',
    },
    'uni_uestc': {
        'name': '电子科技大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_cqu': {
        'name': '重庆大学毕业生就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },

    # --- 西安 ---
    'uni_xjtu': {
        'name': '西安交通大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_nwpu': {
        'name': '西北工业大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },

    # --- 其他985 ---
    'uni_ustc': {
        'name': '中国科学技术大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_xmu': {
        'name': '厦门大学学生就业创业指导中心',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_tju': {
        'name': '天津大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_nankai': {
        'name': '南开大学学生就业指导中心',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_hitu': {
        'name': '哈尔滨工业大学就业网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_jlu': {
        'name': '吉林大学就业网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_dlut': {
        'name': '大连理工大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_neu': {
        'name': '东北大学毕业生就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_sdu': {
        'name': '山东大学学生就业创业指导中心',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_ouc': {
        'name': '中国海洋大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_csu': {
        'name': '中南大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_hnu': {
        'name': '湖南大学毕业生就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_nudt': {
        'name': '国防科技大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_lzu': {
        'name': '兰州大学就业信息网',
        'url': 'https://job.lzu.edu.cn/',
        'enabled': True,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '/html/74/article/list/list_1.html',
        'note': '已支持招聘公告列表爬取',
    },
    'uni_nwafu': {
        'name': '西北农林科技大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_cau': {
        'name': '中国农业大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_muc': {
        'name': '中央民族大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },

    # ======== 财经类大学（重点） ========
    'uni_cufe': {
        'name': '中央财经大学就业信息网',
        'url': 'http://scc.cufe.edu.cn/',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '需分析具体栏目 URL 和列表页 HTML 结构',
    },
    'uni_sufe': {
        'name': '上海财经大学就业网',
        'url': 'https://career.sufe.edu.cn/',
        'enabled': True,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '需分析具体栏目 URL 和列表页 HTML 结构',
    },
    'uni_swufe': {
        'name': '西南财经大学就业信息网',
        'url': 'https://job3.swufe.edu.cn/',
        'enabled': True,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '/jobs/jobs_list.htm',
        'note': '已支持校招职位列表爬取',
    },
    'uni_uibe': {
        'name': '对外经济贸易大学就业网',
        'url': 'http://career.uibe.edu.cn/',
        'enabled': True,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '需分析具体栏目 URL 和列表页 HTML 结构',
    },
    'uni_zuel': {
        'name': '中南财经政法大学就业网',
        'url': 'http://scc.cufe.edu.cn/',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_dufe': {
        'name': '东北财经大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_jufe': {
        'name': '江西财经大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_cueb': {
        'name': '首都经济贸易大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_tjufe': {
        'name': '天津财经大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_sdufe': {
        'name': '山东财经大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_zufe': {
        'name': '浙江财经大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_nufe': {
        'name': '南京财经大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_aufe': {
        'name': '安徽财经大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_gdufe': {
        'name': '广东财经大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_ynufe': {
        'name': '云南财经大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_sxufe': {
        'name': '山西财经大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_xaufe': {
        'name': '西安财经大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_xinjiangufe': {
        'name': '新疆财经大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_imufe': {
        'name': '内蒙古财经大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_jlufe': {
        'name': '吉林财经大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_huel': {
        'name': '河南财经政法大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_heuet': {
        'name': '河北经贸大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_hrbcu': {
        'name': '哈尔滨商业大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_hutb': {
        'name': '湖南工商大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_gzufe': {
        'name': '贵州财经大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_lzufe': {
        'name': '兰州财经大学就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_hbue': {
        'name': '湖北经济学院就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_gxufe': {
        'name': '广西财经学院就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
    'uni_zua': {
        'name': '郑州航空工业管理学院就业信息网',
        'url': '',
        'enabled': False,
        'industries': ['金融', '互联网', '国央企'],
        'type': 'webpage',
        'list_url': '',
        'note': '待补充就业信息网 URL',
    },
}

# ======== 微信公众号数据源（技术限制说明）========
# 微信公众号文章爬取存在以下技术难点：
# 1. 微信公众平台(mp.weixin.qq.com)反爬严格，需要微信登录态
# 2. 搜狗微信搜索(weixin.sogou.com)可搜文章但验证码多、频率限制严
# 3. 文章链接带时效性 token，短期内会失效
# 建议方案：
#   A) 优先爬取学校【就业信息网网页版】（已实现框架，见 UNIVERSITY_SOURCES）
#   B) 公众号作为二期，使用 Selenium/Playwright 模拟浏览器（速度慢但可行）
#   C) 使用第三方服务如新榜/清博 API（需付费）
#   D) 手动关注公众号，通过 RSS 工具（如 WeWe-RSS）间接获取

WECHAT_SOURCES = {
    # 如需实现公众号爬虫，请在此处配置公众号名称/ID，并选择上述方案之一
}

# ======== 行业关键词映射（用于从职位描述中判断行业）========
INDUSTRY_KEYWORDS = {
    '金融': ['银行', '证券', '保险', '基金', '信托', '投行', '金融科技', '财富管理', '资产管理', '量化', '券商', '期货', '租赁', 'AMC', '风投', 'VC', 'PE', '私募', '公募'],
    '互联网': ['互联网', '科技', '软件', '算法', '产品', '运营', '前端', '后端', 'AI', '大数据', '云计算', '电商', '游戏', '新媒体', 'SaaS', '人工智能', '机器学习', '推荐', '搜索', '自动驾驶'],
    '国央企': ['国企', '央企', '集团', '股份', '控股', '中字头', '中国', '国家', '国有', '国资', '中铁', '中建', '中交', '中石油', '中石化', '国家电网', '南方电网', '三大运营商', '邮政', '烟草', '盐业'],
}
